<%@ Page Title="" Language="C#" MasterPageFile="~/outer.Master" AutoEventWireup="true" CodeBehind="Tourism.aspx.cs" Inherits="MeghalayaUIP.Tourism" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <section class="innerpages">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>

                            <li class="breadcrumb-item active" aria-current="page">Priority Sectors</li>
                            <li class="breadcrumb-item active" aria-current="page">Tourism</li>
                        </ol>
                    </nav>
                    <h3>Tourism</h3>
                    <p><b>Meghalaya is ranked 3rd among the North-eastern states for Domestic and Foreign Tourist Visits in the year 2019 as per India Tourism Statistics, 2023</b></p>
                    <p>Meghalaya is a captivating destination known for its beautiful landscapes, vibrant culture, and thrilling adventures. From lush hills to cascading waterfalls and fascinating caves, there's something for everyone to enjoy. Cultural festivals and friendly locals offer a glimpse into the region's rich heritage, while activities like trekking and caving provide excitement. Sustainable tourism efforts help protect the environment and support local communities. Meghalaya is home to remarkable attractions like Asia's cleanest village and India's tallest waterfall. With ongoing improvements to tourism facilities and a focus on responsible travel, Meghalaya continues to attract visitors and foster economic growth.</p>
                    
                    <img src="assets/assetsbeta/images/touistfootfall.jpg" />
                    <img src="assets/assetsbeta/images/TS.png" style="margin-left:3%;" /><br /><br />
                    <%--<p><b>Current statuses of the Tourism sector in Meghalaya</b></p>
                    <ul>
                        <li>1. Tourist footfall: 13.71 lakh (2023) </li>
                        <li>2. Employment opportunities generated by the sector: 50,040 livelihood opportunities</li>
                        <li>3. Targeted Employment Opportunities by 2028:  20 Lakh</li>
                        <li>4. Contribution of Tourism sector to the state's energy reservoir: 4.1%</li>
                        <li>5. Tourist Circuits: 11</li>
                        <li>6. No. of tourist sites: 300+</li>
                    </ul>--%>
                    <%--<p><b>Key projects</b></p>--%>
                    <%--<p>Here are some of the key tourism projects of the State of Meghalaya:</p>
                    <ul>
                        <li>1.	CM- Elevate<br />
The scheme promotes tourism entrepreneurship, that provides financial support and capacity building to local youth to develop quality accommodations (Agri Villas, Motor Caravans) and operate transport services
</li>
                        <li>2.	Shillong Festivals<br />
The state has conducted 3 key festivals Cherry Blossom Festival in Shillong, the Me’gong Festival in Tura, Winter Tales since 2021 to showcase the unique culture, lifestyle & heritage of local communities. 
</li>
                    </ul>--%>
                    <img src="assets/assetsbeta/images/2T.png" style="margin-left:3%;" />
                    </div>
                </div>
            </div>
        </section>
</asp:Content>
